// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "opencitymarket-20181227162717-hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://opencitymarket-20181227162717-hostingbucket.s3-website-us-west-2.amazonaws.com"
};


export default awsmobile;
